W-PTWD-April-2024-Liftoff/dama-devs

backend/build.gradle, backend/src/main/resources/application.properties
updated application.properties for setup with the schema, added plant_data.csv file for prep plant data, updated mySQL dependency
=> Database setup

ui/package-lock.json, ui/package.json, ui/src/App.jsx, ui/src/pages/DashboardPage.jsx, ui/src/pages/ExampleTwo.jsx, ui/src/pages/StarterPage.jsx, ui/src/reusable-code/Dashboard.jsx
- Created a starter page to begin the navigation through the pages
- created a dashboard template that will hold garden pics, 5 day forecast, and nursery locations near user
=> Added dashboard template, starter page

backend/src/main/java/com/launchcode/dama_devs/controllers/CommentController.java, backend/src/main/java/com/launchcode/dama_devs/controllers/GardenController.java, backend/src/main/java/com/launchcode/dama_devs/controllers/PlantController.java, backend/src/main/java/com/launchcode/dama_devs/models/Comment.java, backend/src/main/java/com/launchcode/dama_devs/models/Garden.java, backend/src/main/java/com/launchcode/dama_devs/models/Plant.java, backend/src/main/java/com/launchcode/dama_devs/models/User.java, backend/src/main/java/com/launchcode/dama_devs/models/dto/GardenPlantDTO.java
Base feature. As a DamaDev I need entities in the database to be related to each other so that I can execute many of my features on this project.
**Includes:**
Plant to Garden (Many to Many)
Garden to Plant (Many to Many) 
GardenPlant DTO 
User to Garden (One to Many) 
Garden to User (Many to One) 
Comment to User (Many to One) 
User to Comment (One to Many)
Plant to Comment (One to Many)
Comment to Plant (Many to One) 
Relationships:
Each plant may be related to many instances of gardens (many to many)
Each garden may be related to many instances of plants (many to many)
Each user may be related to many instances of gardens (one to many)
Each garden may be related to only one instance of a user (many to one)
Each comment may be related only one plant (many to one)
Each plant may be …
=> db relationships plants-gardens-comments-users

backend/src/main/java/com/launchcode/dama_devs/controllers/GardenController.java, backend/src/main/java/com/launchcode/dama_devs/models/Plant.java, backend/src/main/java/com/launchcode/dama_devs/models/dto/GardenPlantDTO.java
I created the plant class model and cleaned up the code in the GardenPlant DTO
=> created plant model

backend/src/main/java/com/launchcode/dama_devs/models/Garden.java
Updated Garden Model with getters, setters, constructor, toString method
=> Garden model

backend/src/main/java/com/launchcode/dama_devs/models/Comment.java, backend/src/main/java/com/launchcode/dama_devs/models/Garden.java, backend/src/main/java/com/launchcode/dama_devs/models/Plant.java, backend/src/main/java/com/launchcode/dama_devs/models/User.java, backend/src/main/java/com/launchcode/dama_devs/models/dto/GardenPlantDTO.java
fixed the lombok getters and setters usage
=> fixed lombok getters and setters usage

ui/src/pages/Dashboard.jsx, ui/src/reusable-code/DashboardWeather.jsx
Created the starter page files for React
- HomePage.jsx
- CreateAccount.jsx
- Login.jsx
- AccountSuccess.jsx
- Dashboard.jsx
- DashboardAdmin.jsx
=> Created React Page Files

backend/src/main/java/com/launchcode/dama_devs/DamaDevsApplication.java, ui/package.json
updated csv file path and vite version per security rec to 6.2.3
=> updated csv file path and vite version per security rec

backend/src/main/java/com/launchcode/dama_devs/controllers/GardenController.java, backend/src/main/java/com/launchcode/dama_devs/services/GardenService.java
Hi everyone. This pull request includes updates to the Garden Controller and Garden Service (rendering the existing garden-service branch obsolete).  This ran for me, so hopefully no one has any issues.  Notes...
I was getting stuck on **private final GardenRepository gardenRepository** line in the Garden Service class.  Is "final" needed? 
From what I'm reading outside of LC docs, it is a good practice to make the repository instance in the Service final.  However, if I do make it final in the Service class, I believe that means I cannot instantiate it in the Controller.  As I understand it, the Controller only speaks to the Service (and the Service speaks to the Repository), so it is unnecessary to instantiate the Repository in the Controller at all.  Rather, I just need to instantiate …
=> Garden backend update

backend/src/main/java/com/launchcode/dama_devs/AuthenticationFilter.java, backend/src/main/java/com/launchcode/dama_devs/SecurityConfig.java, backend/src/main/java/com/launchcode/dama_devs/WebApplicationConfig.java, backend/src/main/java/com/launchcode/dama_devs/controllers/GardenController.java, backend/src/main/java/com/launchcode/dama_devs/models/AppRole.java, backend/src/main/java/com/launchcode/dama_devs/models/Role.java, backend/src/main/java/com/launchcode/dama_devs/models/User.java, backend/src/main/java/com/launchcode/dama_devs/models/data/RoleRepository.java, backend/src/main/java/com/launchcode/dama_devs/models/data/UserRepository.java, backend/src/main/java/com/launchcode/dama_devs/services/UserDetailsImpl.java, backend/src/main/java/com/launchcode/dama_devs/services/UserDetailsServiceImpl.java
Hi All , here I updated user model and created two classes of role model and approle enum.
If you have any doubts we will discuss on next meeting.
=> updated user  and created role approle

backend/src/main/java/com/launchcode/dama_devs/controllers/CommentController.java, backend/src/main/java/com/launchcode/dama_devs/controllers/WeatherController.java, backend/src/main/java/com/launchcode/dama_devs/models/Comment.java, backend/src/main/java/com/launchcode/dama_devs/models/data/CommentRepository.java, backend/src/main/java/com/launchcode/dama_devs/services/CommentService.java, ui/src/App.jsx, ui/src/reusable-code/Comment.jsx
Added a Comment.jsx to use in props to inject into PlantPage
Added /comment route to view in React
Updated CommentController 
Updated CommentService
Updated CommentRepository
Updated Comment model
*** Will test once Register User and Plant Data is complete since my repo relies on the foreign keys user_id and plant_id ***
=> Added files for commenting

backend/src/main/java/com/launchcode/dama_devs/SecurityConfig.java, backend/src/main/java/com/launchcode/dama_devs/controllers/AdminController.java, backend/src/main/java/com/launchcode/dama_devs/controllers/CsrfController.java, backend/src/main/java/com/launchcode/dama_devs/models/User.java, backend/src/main/java/com/launchcode/dama_devs/models/data/UserRepository.java, backend/src/main/java/com/launchcode/dama_devs/models/data/UserService.java, backend/src/main/java/com/launchcode/dama_devs/models/dto/UserDTO.java, backend/src/main/java/com/launchcode/dama_devs/services/UserServiceImpl.java
Here y'all can get all users data and get user data using user id and update role of the user using the endpoint starts with /api/admin/** these can be restricted to only admin .
=> csrf token and user service classes created

backend/build.gradle, backend/src/main/java/com/launchcode/dama_devs/SecurityConfig.java, backend/src/main/java/com/launchcode/dama_devs/controllers/AuthController.java, backend/src/main/java/com/launchcode/dama_devs/models/data/UserRepository.java, backend/src/main/java/com/launchcode/dama_devs/models/data/UserService.java, backend/src/main/java/com/launchcode/dama_devs/models/request/LoginRequest.java, backend/src/main/java/com/launchcode/dama_devs/models/request/SignupRequest.java, backend/src/main/java/com/launchcode/dama_devs/models/response/LoginResponse.java, backend/src/main/java/com/launchcode/dama_devs/models/response/MessageResponse.java, backend/src/main/java/com/launchcode/dama_devs/models/response/UserInfoResponse.java, backend/src/main/java/com/launchcode/dama_devs/security/jwt/AuthEntryPointJwt.java, backend/src/main/java/com/launchcode/dama_devs/security/jwt/AuthTokenFilter.java, backend/src/main/java/com/launchcode/dama_devs/security/jwt/JwtUtils.java, backend/src/main/java/com/launchcode/dama_devs/services/UserDetailsImpl.java, backend/src/main/java/com/launchcode/dama_devs/services/UserServiceImpl.java, backend/src/main/resources/application.properties
Now I completed the user can register successfully and user can sign in and get the jwt token.
For Jwt token I wrote some classes please review .
=> User register

backend/src/main/java/com/launchcode/dama_devs/controllers/PhotoController.java, backend/src/main/java/com/launchcode/dama_devs/models/data/GardenRepository.java, backend/src/main/java/com/launchcode/dama_devs/models/data/PhotoRepository.java, backend/src/main/java/com/launchcode/dama_devs/services/GardenService.java, backend/src/main/java/com/launchcode/dama_devs/services/PhotoService.java
- Adjusted code from Long to Integer
- Adjusted Melissa's GardenRepository and GardenService with her permission in this push
=> Adjust code from Long to Integer

backend/src/main/java/com/launchcode/dama_devs/configs/CorsConfig.java, backend/src/main/resources/application.properties, package-lock.json, ui/package-lock.json, ui/package.json, ui/src/.env.development, ui/src/services/api.jsx
Created file in react  to handle the csrf token to get from backend and I register one cors configuration.
=> Handling the csrf token in frontend

ui/package-lock.json, ui/package.json, ui/src/pages/Dashboard.jsx, ui/src/pages/DashboardAdmin.jsx, ui/src/reusable-code/FiveDayForecast.jsx
- Added Material UI weather icons
- Added the zipcode to the Admin Dashboard so it populates the weather forecast once th epage is opened up
=> Ux set weather location admin

backend/src/main/java/com/launchcode/dama_devs/models/Comment.java, backend/src/main/java/com/launchcode/dama_devs/models/Garden.java, backend/src/main/java/com/launchcode/dama_devs/models/Plant.java, backend/src/main/java/com/launchcode/dama_devs/models/User.java, backend/src/main/java/com/launchcode/dama_devs/models/dto/GardenPlantDTO.java
Updated relational mapping to fix recursion issue when using postman to test endpoints.  I also realized comments were missing the mapping in the User model, so I added that.  Not sure if it was accidentally erased or if I had missed it in the previous mapping stories.
=> updated relational mapping to fix recursion

ui/package-lock.json, ui/package.json
updated the json from conflicts
=> updated the package.json with npm install

backend/src/main/resources/application.properties, ui/package.json, ui/src/App.jsx, ui/src/auth/Login.jsx, ui/src/auth/Signup.jsx, ui/src/pages/HomePage.jsx
I just created the user register form and we can successfully register its working.
=> regester form completed

backend/src/main/java/com/launchcode/dama_devs/controllers/CommentController.java, backend/src/main/java/com/launchcode/dama_devs/models/data/CommentRepository.java, backend/src/main/java/com/launchcode/dama_devs/models/dto/CommentDTO.java, backend/src/main/java/com/launchcode/dama_devs/services/CommentService.java, ui/src/App.jsx, ui/src/reusable-code/Comment.jsx
- Add commenting by user and plant id
- Fetching comments by plant id
- Adjusted route in App for testing
- Still need to include upadte comment, delete comment
=> Fixed adding a comment with user and plant id, fetch comments  per plantid

ui/src/App.css, ui/src/App.jsx
=> Fixed scrolling issues

backend/src/main/java/com/launchcode/dama_devs/controllers/PlantController.java, ui/src/pages/PlantDetails.jsx
I haven't tested this yet because I still need to try to figure out how to create an account.  I will do that tonight.  I have a note out to Angie about this because I found a lot of conflicting information in my research today and I wasn't sure what to follow for passing the plantId.
=> Initial work  at fetching plant data for plant details page

ui/src/App.css, ui/src/App.jsx, ui/src/pages/HomePage.jsx, ui/src/reusable-code/NavBar.jsx
- Centered the Routes
- Added a navigation button to the Plant MO Plants title
- Removed the 'v' on Navtive
=> Adjusted the CSS, navigation button

backend/src/main/java/com/launchcode/dama_devs/configs/CorsConfig.java, backend/src/main/java/com/launchcode/dama_devs/controllers/CommentController.java, backend/src/main/java/com/launchcode/dama_devs/services/CommentService.java, ui/src/App.jsx, ui/src/reusable-code/Comment.jsx
- Updated Comment to allow for editing comments
- Commented out weather widget, since not MVP, we can uncomment at any time
- Fixed Css on Comment
- adjusted CORS to allow PUT requests for comments
=> Comment editing

backend/src/main/java/com/launchcode/dama_devs/controllers/PhotoController.java, backend/src/main/java/com/launchcode/dama_devs/models/data/PhotoRepository.java, backend/src/main/java/com/launchcode/dama_devs/services/PhotoService.java, ui/src/App.jsx, ui/src/pages/Dashboard.jsx, ui/src/reusable-code/Comment.jsx, ui/src/reusable-code/NavBar.jsx, ui/src/reusable-code/PhotoFetching.jsx, ui/src/reusable-code/PhotoUpload.jsx
- Users can upload photos and are added to the dashboard, still am working on styling and cleaning up code
- Saves to the database and uploads from database
=> Photo upload backend

ui/src/pages/Dashboard.jsx, ui/src/reusable-code/NurserySearch.jsx
Can now enter zip code to display local nurseries (via dashboard)
=> Nursery Search displayed on Dashboard

ui/src/custom-css/PlantCard.css, ui/src/custom-css/PlantDetails.css, ui/src/custom-css/PlantSearch.css, ui/src/pages/PlantDetails.jsx, ui/src/pages/PlantSearch.jsx, ui/src/reusable-code/PlantCard.jsx
I wanted to push all of this up because it was starting to get big.  I am still working on all of the connections and information flow and working on setting up the results grid.
=> beginning work on plant search page

ui/src/pages/Dashboard.jsx, ui/src/reusable-code/FiveDayForecast.jsx, ui/src/reusable-code/NurserySearch.jsx, ui/src/store/ContextApi.jsx
added zipcode button to auto-update the nurseries list and forecast per current user in the local storage
=> added zipcode button

backend/src/main/java/com/launchcode/dama_devs/SecurityConfig.java, backend/src/main/java/com/launchcode/dama_devs/controllers/GardenController.java, backend/src/main/java/com/launchcode/dama_devs/controllers/PlantController.java, backend/src/main/java/com/launchcode/dama_devs/controllers/RatingController.java, ui/src/pages/PlantDetails.jsx, ui/src/pages/PlantSearch.jsx, ui/src/reusable-code/PlantCard.jsx, ui/src/store/ContextApi.jsx
The plant-search/{gardenId} URL should work now for any logged in user.  All it will do is display a list of that user's plants.  If your get an empty array, check with this garden, because it definitely has matching plants:
INSERT INTO garden (id, garden_light, garden_name, garden_soil, garden_water, garden_zone, user_id) VALUES (1,'full sun',"Bowie Garden",'light','dry','6b',**_YOUR USER ID_**);
=> initial connection fixes for plants

backend/src/main/java/com/launchcode/dama_devs/SecurityConfig.java, backend/src/main/java/com/launchcode/dama_devs/controllers/CommentController.java, backend/src/main/java/com/launchcode/dama_devs/controllers/PhotoController.java, ui/src/reusable-code/Comment.jsx, ui/src/reusable-code/PhotoFetching.jsx, ui/src/reusable-code/PhotoUpload.jsx
updated with User Service, no more 401 error
=> update AuthenticationPrincipal with UserDetailsImpl

backend/src/main/java/com/launchcode/dama_devs/configs/CorsConfig.java, backend/src/main/java/com/launchcode/dama_devs/controllers/GardenController.java, backend/src/main/java/com/launchcode/dama_devs/models/dto/GardenDTO.java, backend/src/main/java/com/launchcode/dama_devs/services/GardenService.java, package-lock.json, package.json, ui/src/App.jsx, ui/src/custom-css/GardenCard.css, ui/src/pages/CreateGarden.jsx, ui/src/pages/GardenConditions.jsx, ui/src/pages/GardenZone.jsx, ui/src/store/GardenContext.jsx
updated with authentication and garden context
=> New garden frontend

backend/src/main/java/com/launchcode/dama_devs/SecurityConfig.java
=> added garden authentication

backend/src/main/java/com/launchcode/dama_devs/SecurityConfig.java, backend/src/main/java/com/launchcode/dama_devs/controllers/CommentController.java, backend/src/main/java/com/launchcode/dama_devs/models/dto/CommentUserDTO.java, ui/src/reusable-code/Comment.jsx
=> Updated comment authentication

ui/src/reusable-code/Comment.jsx
=> Added confirm delete

backend/src/main/java/com/launchcode/dama_devs/controllers/PlantController.java, backend/src/main/java/com/launchcode/dama_devs/models/Garden.java, backend/src/main/java/com/launchcode/dama_devs/models/Plant.java, backend/src/main/java/com/launchcode/dama_devs/models/PlantRating.java, backend/src/main/java/com/launchcode/dama_devs/services/PlantFilteringService.java, ui/src/custom-css/PlantSearch.css, ui/src/pages/PlantSearch.jsx
All of the plant stuff will be broken until this goes through.  I had to remove a bunch of toStrings
=> created by type filter, fixed recursion issues with toString

ui/src/pages/GardenConditions.jsx, ui/src/pages/GardenSuccess.jsx
Matched text and buttons to rest of site
=> Added styling to Garden Success page

ui/src/custom-css/GardenConditions.css, ui/src/custom-css/GardenDetail.css, ui/src/pages/GardenDetails.jsx
Hopefully made it look a little nicer...
=> Updated styling on Garden Details page

backend/src/main/resources/application.properties
I commented out the old line just in case, but I updated this to fix that deprecation warning and everything's running fine.
=> update app properties to address the MySQL dialect warning

backend/src/main/java/com/launchcode/dama_devs/controllers/GardenController.java, backend/src/main/java/com/launchcode/dama_devs/controllers/PlantController.java, backend/src/main/java/com/launchcode/dama_devs/models/data/GardenRepository.java, backend/src/main/java/com/launchcode/dama_devs/services/GardenPlantService.java, backend/src/main/java/com/launchcode/dama_devs/services/PlantFilteringService.java, ui/src/custom-css/PlantCard.css, ui/src/pages/PlantSearch.jsx
I added in authorization to fetching the matching garden plants on the backend.  Now the user has to be authenticated and authorized to view the plants that match their gardens.  I also added more error handling.
=> updated error handling and authorization for searching garden plants

backend/src/main/java/com/launchcode/dama_devs/SecurityConfig.java, backend/src/main/java/com/launchcode/dama_devs/controllers/PhotoController.java, ui/src/App.jsx, ui/src/reusable-code/GardenPhoto.jsx, ui/src/reusable-code/PhotoUpload.jsx
- Updated Photo Upload to save directly to gardenId without having to select from drop down menu of available gardens
=> Photo Upload with better UX
